blank_issues_enabled: false
contact_links:
  - name: Discussion Forum
    url: https://github.com/traponion/jumping-dot-game/discussions
    about: Ask questions and discuss ideas with the community
  - name: Security Issues
    url: https://github.com/traponion/jumping-dot-game/security/advisories/new
    about: Report security vulnerabilities privately