name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Code style checking (Biome)
        run: npm run lint
        
      - name: TypeScript type checking
        run: npm run typecheck
        
      - name: Run tests
        run: npm test

      - name: Run tests with coverage
        run: npm run test:coverage
        
      - name: Build
        run: npm run build
        
      - name: Prepare GitHub Pages deployment
        if: github.ref == 'refs/heads/main'
        run: |
          # Create temporary directory for GitHub Pages deployment
          mkdir -p ./pages-deploy
          # Copy all built assets from dist
          cp -r dist/* ./pages-deploy/
          # Copy additional assets that might be needed
          cp -r public/* ./pages-deploy/ 2>/dev/null || true
        
      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v4
        
      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: './pages-deploy'

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4